### PR TITLE
fix: change getting to delivering

### PR DESCRIPTION
**Pull request by jonyhy96**

### CODE REVIEW

**Comment by waynew** [comment]
Thanks for the PR! However, I'm not sure that this is accurate - `getting data from and getting data to` is entirely valid.

`getting data from and setting data on` might work but I think that would be wrong, too. It would be more like `getting data from and setting configuration on`. But that also sounds pretty weird.

**Comment by jonyhy96** [comment]
> 

How about get from and set to？

**Comment by jonyhy96** [comment]
Use deliver to consistent with description bellow?

**Comment by waynew** [comment]
That does appear grammatically sound - "getting to" is also, though - e.g. "get this to the finish line".

I don't have a strong preference either way.

**Comment by jonyhy96** [comment]
since we don't have better replacements for those words, i will close this pr. Thanks anyway

**Pull request closed without merging**
